- name: Create User
  user:
    name: "{{ item[0] }}"
    password: "{{ item[1] }}"
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{item}}"
  with_together: 
    - "{{ users }}"
    - "{{ passwords }}"
